### PR TITLE
Fix errors on Rust nightly and beta

### PR DESCRIPTION
**Pull request by wmww**
I noticed the build was failing on nightly and beta. This seems to fix it.

### CODE REVIEW

**Comment by WiSaGaN** [comment]
Thanks. Can you fix the failing test?

**Comment by wmww** [comment]
That dyn thing was just to fix a warning, so I just reverted it.

**Comment by wmww** [comment]
I don't fully understand the problem. Also, works on my machine (rustc 1.35.0 as well)

**Comment by WiSaGaN** [comment]
I added a regression test in master to make sure that changes to fix the inference would not break existing code. We will need to make the fix to pass the test for the merge request to land.

**Comment by WiSaGaN** [comment]
Fixed in newly released 0.2.1. Thanks for the merge request anyway.

**Pull request closed without merging**
